Repository doctrine/mongodb-odm, pull requests merged in 2018-09, with the labels that each got.

#1858 Update homepage
  composer.json
Labels: documentation

#1840 [1.3] Deprecate setDefaultRepositoryClassName and getDefaultRepositoryClassName
  lib/Doctrine/ODM/MongoDB/Configuration.php
  lib/Doctrine/ODM/MongoDB/Repository/AbstractRepositoryFactory.php
Labels: task

#1841 [1.3] Deprecate passing bool to autogenerate methods.
  lib/Doctrine/ODM/MongoDB/Configuration.php
Labels: task

#1772 Deprecate combining repositoryMethod with skip, sort and limit
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php
Labels: task

#1856 Add UPGRADE document for ODM 2.0
  UPGRADE-1.2.md
  UPGRADE-2.0.md
Labels: documentation

#1867 Update PHPStan
  .travis.yml
  composer.json
  lib/Doctrine/ODM/MongoDB/Query/QueryExpressionVisitor.php
  phpstan.neon.dist
Labels: task

#1866 Replace QueryLogger in tests with CommandLogger
  lib/Doctrine/ODM/MongoDB/APM/Command.php
  lib/Doctrine/ODM/MongoDB/APM/CommandLogger.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/AtomicSetTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/CommitImprovementTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ShardKeyTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1138Test.php
  tests/Doctrine/ODM/MongoDB/Tests/QueryLogger.php
Labels: feature
