Repository doctrine/mongodb-odm, pull requests merged in 2018-07, with the labels that each got.

#1828 Improve SchemaManager logic for comparing text indexes
  lib/Doctrine/ODM/MongoDB/SchemaManager.php
  tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
Labels: bug

#1829 Improve SchemaManager logic for comparing text indexes
  lib/Doctrine/ODM/MongoDB/SchemaManager.php
  tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
Labels: bug

#1831 [2.0] Fix wrong element deletion in popFirst and popLast
  lib/Doctrine/ODM/MongoDB/Query/Expr.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/QueryTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/ExprTest.php
Labels: bug

#1819 Improvements
  lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
  lib/Doctrine/ODM/MongoDB/Configuration.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  lib/Doctrine/ODM/MongoDB/Query/Builder.php
  lib/Doctrine/ODM/MongoDB/Query/Expr.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/DropCommand.php
  lib/Doctrine/ODM/MongoDB/Types/CustomIdType.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
Labels: task

#1814 [2.0] Validate mapping files against schema
  doctrine-mongo-mapping.xsd
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/XmlDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.UserNonStringOptions.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/XmlMappingDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.InvalidMappingDocument.dcm.xml
Labels: BC break, feature, needs-1.3-compat-layer

#1834 [2.0] Consistently use kebab-case in XML mappings
  doctrine-mongo-mapping.xsd
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.xml
Labels: BC break, needs-1.3-compat-layer, task

#1836 Added dev autoload for composer & removed it from tests boostrap.
  composer.json
  tests/bootstrap.php
Labels: task
