Repository doctrine/mongodb-odm, pull requests merged in 2018-11, with the labels that each got.

#1875 Drop doctrine/common proxies in favor of ProxyManager
  UPGRADE-2.0.md
  composer.json
  docs/en/cookbook/blending-orm-and-mongodb-odm.rst
  lib/Doctrine/ODM/MongoDB/Configuration.php
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  lib/Doctrine/ODM/MongoDB/Proxy/ClassNameResolver.php
  lib/Doctrine/ODM/MongoDB/Proxy/Factory/ProxyFactory.php
  lib/Doctrine/ODM/MongoDB/Proxy/Factory/StaticProxyFactory.php
  lib/Doctrine/ODM/MongoDB/Proxy/ProxyFactory.php
  lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateProxiesCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  tests/Doctrine/ODM/MongoDB/Tests/DocumentManagerTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/DetachedDocumentTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/IdentifiersTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencePrimerTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencesTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/SimpleReferencesTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH520Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH593Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH602Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH852Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH936Test.php
  tests/Doctrine/ODM/MongoDB/Tests/HydratorTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataFactoryTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
  tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
  tests/Doctrine/ODM/MongoDB/Tests/UnitOfWorkTest.php
  tests/Stubs/DocumentManager.php
Labels: BC break, documentation, feature, needs-1.3-compat-layer

#1891 Fix fieldName with field-name
  docs/en/reference/xml-mapping.rst
Labels: documentation

#1892 Use dedicated assertContainsOnlyInstancesOf assertion
  tests/Doctrine/ODM/MongoDB/Tests/Functional/DiscriminatorsDefaultValueTest.php
Labels: task

#1893 Fix missing proxy directory
  lib/Doctrine/ODM/MongoDB/Configuration.php
  lib/Doctrine/ODM/MongoDB/Proxy/FileLocator.php
  tests/Doctrine/ODM/MongoDB/Tests/BaseTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/IndexesTest.php
Labels: bug

#1899 Error in group aggregation builder
  docs/en/reference/aggregation-builder.rst
Labels: documentation

#1894 Fix inheritance of GridFS mapping properties
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/File.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/BasicInheritanceMappingTest.php
Labels: bug

#1896 Drop dependency on doctrine/common
  composer.json
  lib/Doctrine/ODM/MongoDB/Proxy/Proxy.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/QueryCommand.php
Labels: BC break, task

#1895 Drop "simple" attribute from references in XML schema
  doctrine-mongo-mapping.xsd
  lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
  lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php
  tests/Doctrine/ODM/MongoDB/Tests/DocumentManagerTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
Labels: BC break, task

#1904 Always use dump method from VarDumper component
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/QueryCommand.php
Labels: bug

#1902 Remove eager cursor functionality without replacement
  UPGRADE-2.0.md
  docs/en/reference/eager-cursors.rst
  docs/en/reference/priming-references.rst
  docs/en/reference/query-builder-api.rst
  docs/en/sidebar.rst
  lib/Doctrine/ODM/MongoDB/Query/Builder.php
  lib/Doctrine/ODM/MongoDB/Query/Query.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencePrimerTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH852Test.php
  tests/Documents/BlogPost.php
  tests/Documents/CommentRepository.php
Labels: BC break, needs-1.3-compat-layer

#1901 Fix skipped tests
  tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencePrimerTest.php
Labels: task

#1903 Throw exception on duplicate database names within a document
  UPGRADE-2.0.md
  docs/en/reference/annotations-reference.rst
  docs/en/reference/migrating-schemas.rst
  docs/en/reference/query-builder-api.rst
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/AbstractField.php
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/NotSaved.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/AlsoLoadTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/OwningAndInverseReferencesTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/XmlMappingDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverDuplicateDatabaseName.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverDuplicateDatabaseNameNotSaved.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverSuperClass.dcm.xml
  tests/Documents/Customer.php
  tests/Documents/Functional/NotSaved.php
  tests/Documents/Functional/NotSavedEmbedded.php
  tests/Documents/User.php
Labels: BC break, bug, needs-1.3-compat-layer
