Repository doctrine/mongodb-odm, pull requests merged in 2018-12, with the labels that each got.

#1909 Update chat link from Gitter to Slack.
  docs/en/index.rst
Labels: documentation

#1880 Optimized nested collections deletion in DocumentPersister
  lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/CollectionPersisterTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/LockTest.php
Labels: BC break, needs-1.3-compat-layer

#1913 Update changelog for 2.0.0-Beta1
  CHANGELOG-2.0.md
Labels: documentation

#1915 Use Ubuntu 16.04
  .travis.yml
Labels: Enhancement
