Repository doctrine/mongodb-odm, pull requests merged in 2018-05, with the labels that each got.

#1792 Implicitly cascade remove operations when orphanRemoval is enabled
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/OrphanRemovalTest.php
Labels: bug

#1793 Fix querying fields in reference structures
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/QueryTest.php
  tests/Doctrine/ODM/MongoDB/Tests/QueryTest.php
  tests/Documents/IndirectlyReferencedUser.php
  tests/Documents/ReferenceUser.php
Labels: bug

#1800 Fix new CS violations
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ODM/MongoDB/PersistentCollection/DefaultPersistentCollectionGenerator.php
  lib/Doctrine/ODM/MongoDB/Proxy/ProxyFactory.php
  lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
Labels: task

#1798 [2.0] Fix querying fields in reference structures
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/QueryTest.php
  tests/Doctrine/ODM/MongoDB/Tests/QueryTest.php
  tests/Documents/IndirectlyReferencedUser.php
  tests/Documents/ReferenceUser.php
Labels: bug

#1797 [2.0] Implicitly cascade remove operations when orphanRemoval is enabled
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/OrphanRemovalTest.php
Labels: bug

#1802 [2.0] Drop bool from supported values - Configuration class
  lib/Doctrine/ODM/MongoDB/Configuration.php
Labels: BC break, task
