Repository doctrine/mongodb-odm, pull requests merged in 2018-04, with the labels that each got.

#1771 [2.0] Forbid combining repositoryMethod with skip, sort and limit
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
Labels: BC break, task

#1777 [1.0.x] Remove | separators
  docs/en/index.rst
Labels: documentation

#1778 [1.1.x] Remove | separators
  docs/en/index.rst
Labels: documentation

#1779 [1.2.x] Remove | separators
  docs/en/index.rst
Labels: documentation

#1780 [2.0] Remove | separators
  docs/en/index.rst
Labels: documentation

#1760 Move coverage to Code Quality stage
  .travis.yml
Labels: task

#1786 [2.0] Fix hydration of proxy objects with lazy public properties
  lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1775Test.php
Labels: bug
