Repository doctrine/mongodb-odm, pull requests merged in 2019-11, with the labels that each got.

#2085 Cast also-load xml attribute to string
  composer.json
  doctrine-mongo-mapping.xsd
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/AbstractDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/XmlDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/AlsoLoadDocument.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.AlsoLoadDocument.dcm.xml
Labels: Bug

#2097 Fix wrong handling of custom identifier names
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/yaml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.yml
Labels: Bug

#2100 Remove reference to generators on iterator destruction
  lib/Doctrine/ODM/MongoDB/Iterator/CachingIterator.php
  lib/Doctrine/ODM/MongoDB/Iterator/HydratingIterator.php
Labels: Bug, Easy Pick

#2110 [Doc] Remove dropped commands
  docs/en/reference/console-commands.rst
Labels: Documentation

#2111 remove repeated sidebar section
  docs/en/sidebar.rst
Labels: Documentation

#2108 Fix merging of documents when not cascading references
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/DetachedDocumentTest.php
Labels: Bug

#2114 Ignore index name changes
  lib/Doctrine/ODM/MongoDB/SchemaManager.php
  tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
Labels: Bug

#2117 Add console commands and upserting chapters
  docs/en/sidebar.rst
Labels: Documentation

#2115 Symfony 5 support
  composer.json
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/ClearCache/MetadataCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/ConvertMappingToXmlCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateDocumentsCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateHydratorsCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GeneratePersistentCollectionsCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateProxiesCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateRepositoriesCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/QueryCommand.php
Labels: Enhancement

#2123 Remove unneceesary internal designations
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
Labels: Enhancement

#2118 Add DateImmutable type
  docs/en/reference/annotations-reference.rst
  docs/en/reference/basic-mapping.rst
  docs/en/reference/transactions-and-concurrency.rst
  lib/Doctrine/ODM/MongoDB/LockException.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  lib/Doctrine/ODM/MongoDB/Types/DateImmutableType.php
  lib/Doctrine/ODM/MongoDB/Types/DateType.php
  lib/Doctrine/ODM/MongoDB/Types/Type.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/LockTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Types/DateImmutableTypeTest.php
Labels: Feature
