Repository doctrine/mongodb-odm, pull requests merged in 2019-10, with the labels that each got.

#2061 Flipped key/value for SimplifiedXmlDriver example
  docs/en/reference/xml-mapping.rst
Labels: Documentation

#2074 Remove references to legacy documentation
  docs/en/reference/aggregation-builder.rst
  docs/en/reference/annotations-reference.rst
  docs/en/reference/architecture.rst
  docs/en/reference/basic-mapping.rst
  docs/en/reference/indexes.rst
  docs/en/reference/introduction.rst
  docs/en/reference/storing-files-with-gridfs.rst
  docs/en/sidebar.rst
Labels: Documentation

#2069 Class name resolver performance optimisation
  UPGRADE-2.0.md
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  lib/Doctrine/ODM/MongoDB/Proxy/Resolver/CachingClassNameResolver.php
  lib/Doctrine/ODM/MongoDB/Proxy/Resolver/ClassNameResolver.php
  lib/Doctrine/ODM/MongoDB/Proxy/Resolver/ProxyManagerClassNameResolver.php
Labels: BC Break

#2075 Update supported versions in documentation
  .doctrine-project.json
Labels: Documentation

#2073 Throw hydrator exceptions when encountering invalid types
  lib/Doctrine/ODM/MongoDB/Hydrator/HydratorException.php
  lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  tests/Doctrine/ODM/MongoDB/Tests/HydratorTest.php
Labels: Bug

#2065 Add command example to create a capped collection
  docs/en/reference/capped-collections.rst
Labels: Documentation

#2076 Use expectException(Message) instead of annotations
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/ExprTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/OutTest.php
  tests/Doctrine/ODM/MongoDB/Tests/DocumentManagerTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/CustomCollectionsTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/CustomTypeTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/EmbeddedIdTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/FunctionalTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/IdTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/IndexesTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Iterator/CachingIteratorTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/LockTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/QueryTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencePrimerTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencesTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ShardKeyTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH850Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH971Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/AnnotationDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/BasicInheritanceMappingTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ShardKeyInheritanceMappingTest.php
  tests/Doctrine/ODM/MongoDB/Tests/PersistentCollectionTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/BuilderTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/ExprTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/Filter/BsonFilterTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/FilterCollectionTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/QueryExpressionVisitorTest.php
  tests/Doctrine/ODM/MongoDB/Tests/QueryTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Types/DateTypeTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Types/InvalidValueExceptionTest.php
  tests/Doctrine/ODM/MongoDB/Tests/UnitOfWorkTest.php
Labels: Task

#2081 Move custom type to a separate chapter
  docs/en/reference/basic-mapping.rst
  docs/en/reference/custom-mapping-types.rst
  docs/en/sidebar.rst
Labels: Documentation

#2082 Fix wrong initialisation of proxies with public properties
  lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php
  tests/Doctrine/ODM/MongoDB/Tests/HydratorTest.php
Labels: Bug

#2091 Change returned type references in query builder documentation
  UPGRADE-2.0.md
  docs/en/reference/query-builder-api.rst
Labels: BC Break, Documentation

#2094 Fix hanging upload when not specifying chunk size
  lib/Doctrine/ODM/MongoDB/Repository/DefaultGridFSRepository.php
  tests/Doctrine/ODM/MongoDB/Tests/Repository/DefaultGridFSRepositoryTest.php
  tests/Documents/FileWithoutChunkSize.php
Labels: Bug
