Repository doctrine/mongodb-odm, pull requests merged in 2019-03, with the labels that each got.

#1963 Test against supported versions of MongoDB
  .travis.yml
Labels: Enhancement

#1962 Fix wrong usage of discriminator map in complex document inheritance chains
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1962Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/BuilderTest.php
Labels: Bug

#1967 Add missing `addFields` method for Stage abstract
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage.php
Labels: Bug

#1966 Fix embedding documents containing named indexes
  docs/en/reference/annotations-reference.rst
  docs/en/reference/indexes.rst
  lib/Doctrine/ODM/MongoDB/SchemaManager.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1344Test.php
Labels: Bug

#1971 Clarify deprecation of update() and multiple()
  docs/en/reference/query-builder-api.rst
Labels: Documentation

#1978 Revert "Fix wrong usage of discriminator map in complex document inheritance chains"
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1962Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/BuilderTest.php
Labels: Bug

#1977 [1.2] Fix sharding commands for MongoDB 4.0
  .travis.yml
  lib/Doctrine/ODM/MongoDB/SchemaManager.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/EnsureShardingTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ShardKeyTest.php
  tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
  tests/Documents/Sharded/ShardedOne.php
Labels: Bug

#1960 Mark methods and classes as internal
  UPGRADE-2.0.md
  lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionInterface.php
  lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
  lib/Doctrine/ODM/MongoDB/Proxy/FileLocator.php
  lib/Doctrine/ODM/MongoDB/Query/QueryExpressionVisitor.php
  lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
Labels: Task

#1965 Fix wrong behavior of sortMeta
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1964Test.php
Labels: Bug

#1983 Allow returning null from getAssociationTargetClass
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
Labels: Bug
