Repository doctrine/mongodb-odm, pull requests merged in 2019-04, with the labels that each got.

#1972 [1.3] Use build stages in .travis.yml
  .travis.yml
Labels: Task

#1989 Fix metadata storage when uploading GridFS files
  lib/Doctrine/ODM/MongoDB/Repository/DefaultGridFSRepository.php
  tests/Doctrine/ODM/MongoDB/Tests/Repository/DefaultGridFSRepositoryTest.php
  tests/Documents/FileMetadata.php
Labels: Bug

#1991 Fix generation of proxy classes
  lib/Doctrine/ODM/MongoDB/Proxy/Factory/StaticProxyFactory.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1990Test.php
Labels: Bug

#1996 Fix dir permissions for proxies
  lib/Doctrine/ODM/MongoDB/Proxy/FileLocator.php
Labels: Bug

#2001 Provide deprecation notices for deprecated query types
  UPGRADE-1.3.md
  lib/Doctrine/ODM/MongoDB/Query/Builder.php
  lib/Doctrine/ODM/MongoDB/Query/Query.php
Labels: Enhancement

#1956 Remove previously deprecated operations from Query Builder
  UPGRADE-2.0.md
  docs/en/reference/map-reduce.rst
  docs/en/reference/query-builder-api.rst
  docs/en/sidebar.rst
  lib/Doctrine/ODM/MongoDB/Query/Builder.php
  lib/Doctrine/ODM/MongoDB/Query/Query.php
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/LookupTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/BuilderTest.php
Labels: BC Break

#1998 Introducing class metadata not found
  composer.json
  docs/en/reference/events.rst
  lib/Doctrine/ODM/MongoDB/Event/OnClassMetadataNotFoundEventArgs.php
  lib/Doctrine/ODM/MongoDB/Events.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
  tests/Doctrine/ODM/MongoDB/Tests/Events/OnClassMetadataNotFoundEventArgsTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataFactoryTest.php
Labels: Feature

#2007 Loosen naming rules for discriminator values
  doctrine-mongo-mapping.xsd
Labels: Enhancement

#2006 Run appropriate query operations when replacing documents
  lib/Doctrine/ODM/MongoDB/Query/Query.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/QueryTest.php
Labels: Bug

#2008 Mark classes as @final and deprecate extending them
  lib/Doctrine/ODM/MongoDB/DocumentNotFoundException.php
  lib/Doctrine/ODM/MongoDB/Event/DocumentNotFoundEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/LoadClassMetadataEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/OnClassMetadataNotFoundEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/OnClearEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/OnFlushEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/PostCollectionLoadEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/PostFlushEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/PreFlushEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/PreLoadEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/PreUpdateEventArgs.php
  lib/Doctrine/ODM/MongoDB/Hydrator/HydratorException.php
  lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php
  lib/Doctrine/ODM/MongoDB/Id/AlnumGenerator.php
  lib/Doctrine/ODM/MongoDB/Id/AutoGenerator.php
  lib/Doctrine/ODM/MongoDB/Id/IncrementGenerator.php
  lib/Doctrine/ODM/MongoDB/Id/UuidGenerator.php
  lib/Doctrine/ODM/MongoDB/LockException.php
  lib/Doctrine/ODM/MongoDB/LockMode.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
  lib/Doctrine/ODM/MongoDB/PersistentCollection.php
  lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionException.php
  lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
  lib/Doctrine/ODM/MongoDB/Query/CriteriaMerger.php
  lib/Doctrine/ODM/MongoDB/Query/FilterCollection.php
  lib/Doctrine/ODM/MongoDB/Query/Query.php
  lib/Doctrine/ODM/MongoDB/Query/QueryExpressionVisitor.php
  lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php
  lib/Doctrine/ODM/MongoDB/SchemaManager.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  lib/Doctrine/ODM/MongoDB/Utility/CollectionHelper.php
  lib/Doctrine/ODM/MongoDB/Utility/LifecycleEventManager.php
Labels: Task

#1997 Change `ResolveTargetDocumentListener` to be an event subscriber instead of an event listener
  UPGRADE-1.3.md
  docs/en/cookbook/resolve-target-document-listener.rst
  lib/Doctrine/ODM/MongoDB/Tools/ResolveTargetDocumentListener.php
  tests/Doctrine/ODM/MongoDB/Tests/Tools/ResolveTargetDocumentListenerTest.php
Labels: Feature

#2013 Update default reference primier's code
  docs/en/reference/priming-references.rst
Labels: Documentation

#1984 Mark classes as final
  UPGRADE-2.0.md
  lib/Doctrine/ODM/MongoDB/DocumentNotFoundException.php
  lib/Doctrine/ODM/MongoDB/Event/DocumentNotFoundEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/LoadClassMetadataEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/OnClassMetadataNotFoundEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/OnClearEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/OnFlushEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/PostCollectionLoadEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/PostFlushEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/PreFlushEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/PreLoadEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/PreUpdateEventArgs.php
  lib/Doctrine/ODM/MongoDB/Hydrator/HydratorException.php
  lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php
  lib/Doctrine/ODM/MongoDB/Id/AlnumGenerator.php
  lib/Doctrine/ODM/MongoDB/Id/AutoGenerator.php
  lib/Doctrine/ODM/MongoDB/Id/IncrementGenerator.php
  lib/Doctrine/ODM/MongoDB/Id/UuidGenerator.php
  lib/Doctrine/ODM/MongoDB/LockException.php
  lib/Doctrine/ODM/MongoDB/LockMode.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
  lib/Doctrine/ODM/MongoDB/PersistentCollection.php
  lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionException.php
  lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
  lib/Doctrine/ODM/MongoDB/Proxy/Factory/StaticProxyFactory.php
  lib/Doctrine/ODM/MongoDB/Query/CriteriaMerger.php
  lib/Doctrine/ODM/MongoDB/Query/FilterCollection.php
  lib/Doctrine/ODM/MongoDB/Query/Query.php
  lib/Doctrine/ODM/MongoDB/Query/QueryExpressionVisitor.php
  lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php
  lib/Doctrine/ODM/MongoDB/SchemaManager.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  lib/Doctrine/ODM/MongoDB/Utility/CollectionHelper.php
  lib/Doctrine/ODM/MongoDB/Utility/LifecycleEventManager.php
  phpstan.neon.dist
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Iterator/PrimingIteratorTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataFactoryTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mocks/ClassMetadataMock.php
  tests/Doctrine/ODM/MongoDB/Tests/Mocks/DocumentManagerMock.php
  tests/Doctrine/ODM/MongoDB/Tests/Mocks/DocumentPersisterMock.php
  tests/Doctrine/ODM/MongoDB/Tests/Mocks/MetadataDriverMock.php
  tests/Doctrine/ODM/MongoDB/Tests/PersistentCollectionTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/ExprTest.php
  tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
  tests/Doctrine/ODM/MongoDB/Tests/UnitOfWorkTest.php
  tests/Documents/Profile.php
  tests/Documents/User.php
  tests/Stubs/DocumentManager.php
Labels: Task

#2012 Document more BC breaks
  UPGRADE-1.3.md
  lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Bucket.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/BucketAuto.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/GraphLookup.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Match.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/ReplaceRoot.php
  lib/Doctrine/ODM/MongoDB/CommandCursor.php
  lib/Doctrine/ODM/MongoDB/Configuration.php
  lib/Doctrine/ODM/MongoDB/Cursor.php
  lib/Doctrine/ODM/MongoDB/DocumentRepository.php
  lib/Doctrine/ODM/MongoDB/EagerCursor.php
  lib/Doctrine/ODM/MongoDB/Iterator/Iterator.php
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Distance.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/MongoDBException.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  lib/Doctrine/ODM/MongoDB/Query/Builder.php
  lib/Doctrine/ODM/MongoDB/Query/Expr.php
  lib/Doctrine/ODM/MongoDB/Query/Query.php
  lib/Doctrine/ODM/MongoDB/Repository/DocumentRepository.php
  lib/Doctrine/ODM/MongoDB/Types/Type.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/OrphanRemovalEmbedTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/OrphanRemovalTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1232Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1572Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
  tests/Documents/BaseCategoryRepository.php
  tests/Documents/CommentRepository.php
  tests/Documents/CustomRepository/Repository.php
  tools/sandbox/Documents/UserRepository.php
Labels: Documentation

#2005 Fix discriminator handling with partial discriminator maps
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2002Test.php
Labels: Bug

#1911 Rework index equivalency checks
  lib/Doctrine/ODM/MongoDB/SchemaManager.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
  tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
Labels: Task

#2021 Dump xdebug filter to improve code coverage build performance
  .travis.yml
  composer.json
Labels: Enhancement

#2020 Make addStage Aggregation Builder method public
  lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage.php
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/BuilderTest.php
Labels: Enhancement

#2022 Reword most deprecation notices
  lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Bucket.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/BucketAuto.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/GraphLookup.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Match.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/ReplaceRoot.php
  lib/Doctrine/ODM/MongoDB/Configuration.php
  lib/Doctrine/ODM/MongoDB/Cursor.php
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  lib/Doctrine/ODM/MongoDB/DocumentNotFoundException.php
  lib/Doctrine/ODM/MongoDB/DocumentRepository.php
  lib/Doctrine/ODM/MongoDB/Event/DocumentNotFoundEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/LoadClassMetadataEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/OnClassMetadataNotFoundEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/OnClearEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/OnFlushEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/PostCollectionLoadEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/PostFlushEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/PreFlushEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/PreLoadEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/PreUpdateEventArgs.php
  lib/Doctrine/ODM/MongoDB/Hydrator/HydratorException.php
  lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php
  lib/Doctrine/ODM/MongoDB/Id/AlnumGenerator.php
  lib/Doctrine/ODM/MongoDB/Id/AutoGenerator.php
  lib/Doctrine/ODM/MongoDB/Id/IncrementGenerator.php
  lib/Doctrine/ODM/MongoDB/Id/UuidGenerator.php
  lib/Doctrine/ODM/MongoDB/LockException.php
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/DoctrineAnnotations.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/SimplifiedYamlDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/YamlDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
  lib/Doctrine/ODM/MongoDB/MongoDBException.php
  lib/Doctrine/ODM/MongoDB/PersistentCollection.php
  lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionException.php
  lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
  lib/Doctrine/ODM/MongoDB/Query/Builder.php
  lib/Doctrine/ODM/MongoDB/Query/CriteriaMerger.php
  lib/Doctrine/ODM/MongoDB/Query/Expr.php
  lib/Doctrine/ODM/MongoDB/Query/FieldExtractor.php
  lib/Doctrine/ODM/MongoDB/Query/FilterCollection.php
  lib/Doctrine/ODM/MongoDB/Query/Query.php
  lib/Doctrine/ODM/MongoDB/Query/QueryExpressionVisitor.php
  lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php
  lib/Doctrine/ODM/MongoDB/Repository/DefaultRepositoryFactory.php
  lib/Doctrine/ODM/MongoDB/Repository/DocumentRepository.php
  lib/Doctrine/ODM/MongoDB/SchemaManager.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/AbstractCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
  lib/Doctrine/ODM/MongoDB/Types/IncrementType.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  lib/Doctrine/ODM/MongoDB/Utility/CollectionHelper.php
  lib/Doctrine/ODM/MongoDB/Utility/LifecycleEventManager.php
Labels: Documentation

#1730 Converter to XML for mapping
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/ConvertMappingToXmlCommand.php
Labels: Feature
