Repository doctrine/mongodb-odm, pull requests merged in 2019-09, with the labels that each got.

#2053 Fix EmbedMany documentation samples
  docs/en/reference/embedded-mapping.rst
Labels: Documentation

#2055 Disable retryable writes on travis-ci
  .travis.yml
Labels: Task

#2056 Modernise tests
  .travis.yml
  .travis/configurations/replica_sets/replicaset.json
  .travis/configurations/sharded_clusters/cluster.json
  .travis/configurations/sharded_clusters/cluster_replset.json
  .travis/configurations/standalone/standalone-auth.json
  .travis/configurations/standalone/standalone.json
  .travis/mo.sh
  .travis/setup_mo.sh
  composer.json
  lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php
  phpunit.xml.dist
  tests/sharded.json
Labels: Task

#2060 Follow-up tasks for build modernisation
  .travis.yml
  .travis/setup_mo.sh
  .travis/setup_mongodb.sh
  phpunit.xml.dist
Labels: Task

#2023 Performance benchmark
  .travis.yml
  benchmark/BaseBench.php
  benchmark/Document/HydrateDocumentBench.php
  benchmark/Document/LoadDocumentBench.php
  benchmark/Document/StoreDocumentBench.php
  composer.json
  phpbench.json
  tests/bootstrap.php
Labels: Task

#2059 Introduce interface for command loggers
  lib/Doctrine/ODM/MongoDB/APM/CommandLogger.php
  lib/Doctrine/ODM/MongoDB/APM/CommandLoggerInterface.php
Labels: Enhancement

#2062 Optimise build configuration
  .travis.yml
Labels: Enhancement

#2064 Add missing deprecation notice for incomplete embedded associations
  lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
Labels: Enhancement
