Repository doctrine/mongodb-odm, pull requests merged in 2019-02, with the labels that each got.

#1947 Remove usage of deprecated ClassMetadataInfo class in hydrators
  lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php
Labels: Task

#1946 [1.3] Rename scheduleForDirtyFlag
  lib/Doctrine/ODM/MongoDB/PersistentCollection/DefaultPersistentCollectionGenerator.php
  lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  tests/Doctrine/ODM/MongoDB/Tests/UnitOfWorkTest.php
Labels: Task

#1934 Documenting Lookup not working on ref which are in embedded doc.
  docs/en/reference/aggregation-builder.rst
Labels: Documentation

#1949 [1.3] Deprecate proxies from doctrine/common
  UPGRADE-1.3.md
  lib/Doctrine/ODM/MongoDB/Configuration.php
  lib/Doctrine/ODM/MongoDB/Proxy/Proxy.php
  lib/Doctrine/ODM/MongoDB/Proxy/ProxyFactory.php
Labels: Task

#1950 [1.3] Deprecate GridFS mappings
  UPGRADE-1.3.md
  doctrine-mongo-mapping.xsd
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/File.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ODM/MongoDB/Types/FileType.php
Labels: Task

#1948 [1.3] Optimize nested collection deletions
  UPGRADE-1.3.md
  lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/CollectionPersisterTest.php
Labels: Feature

#1951 [2.0] Add PHP 7.4snapshot to build pipeline
  .travis.yml
Labels: Task

#1952 Clarify deprecation block for same-namespace resolution
  UPGRADE-1.3.md
Labels: Documentation

#1953 [2.0] Add missing documentation of same-namespace resolution drop
  UPGRADE-2.0.md
Labels: Documentation

#1958 Allow Symfony 3.4
  composer.json
Labels: Enhancement

#1954 Document autoload requirement for generated proxies
  docs/en/reference/introduction.rst
  docs/en/tutorials/getting-started.rst
Labels: Documentation

#1693 Schema manager should handle shard key on reference
  lib/Doctrine/ODM/MongoDB/SchemaManager.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/EnsureShardingTest.php
  tests/Documents/Sharded/ShardedByUser.php
Labels: Enhancement
