Repository doctrine/mongodb-odm, pull requests merged in 2019-01, with the labels that each got.

#1919 Replace the deprecated comment
  doctrine-mongo-mapping.xsd
Labels: bug

#1922 Fix wrong usage of sequence vs. choice in XSD
  doctrine-mongo-mapping.xsd
Labels: bug

#1926 Fix wrong capitalisation of attributes for GridFS mappings
  docs/en/cookbook/mapping-classes-to-orm-and-odm.rst
  docs/en/reference/aggregation-builder.rst
  docs/en/reference/basic-mapping.rst
  docs/en/reference/capped-collections.rst
  docs/en/reference/indexes.rst
  docs/en/reference/reference-mapping.rst
  docs/en/reference/storing-files-with-mongogridfs.rst
  docs/en/reference/transactions-and-concurrency.rst
  docs/en/reference/xml-mapping.rst
  docs/en/tutorials/getting-started.rst
  doctrine-mongo-mapping.xsd
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverFile.dcm.xml
Labels: BC break, bug

#1924 Add deprecation layers
  UPGRADE-1.3.md
  docs/en/reference/basic-mapping.rst
  docs/en/reference/capped-collections.rst
  docs/en/reference/indexes.rst
  docs/en/reference/xml-mapping.rst
  docs/en/tutorials/getting-started.rst
  doctrine-mongo-mapping.xsd
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/GraphLookup.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Lookup.php
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/ReferenceMany.php
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/ReferenceOne.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/SimplifiedYamlDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/YamlDriver.php
  lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
  lib/Doctrine/ODM/MongoDB/Proxy/ProxyFactory.php
  lib/Doctrine/ODM/MongoDB/Query/Builder.php
  lib/Doctrine/ODM/MongoDB/Query/Expr.php
  lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php
  lib/Doctrine/ODM/MongoDB/SchemaManager.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GeneratePersistentCollectionsCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/DisconnectedClassMetadataFactory.php
  lib/Doctrine/ODM/MongoDB/Tools/DocumentGenerator.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  lib/Doctrine/ODM/MongoDB/Utility/CollectionHelper.php
  tests/Doctrine/ODM/MongoDB/Tests/DocumentManagerTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/CustomCollectionsTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/NestedCollectionsTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencePrimerTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1275Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataInfoTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/AbstractDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/XmlDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.UserCustomIdGeneratorWithIdField.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/XmlMappingDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/ExprTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Tools/DocumentGeneratorTest.php
  tests/Documents/Article.php
  tests/Documents/User.php
Labels: feature

#1927 Deprecate more features in preparation for 2.0
  UPGRADE-1.3.md
  docs/en/reference/annotations-reference.rst
  docs/en/reference/indexes.rst
  docs/en/reference/migrating-schemas.rst
  docs/en/reference/query-builder-api.rst
  doctrine-mongo-mapping.xsd
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/AbstractField.php
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/AbstractIndex.php
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/NotSaved.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ODM/MongoDB/Query/Builder.php
  lib/Doctrine/ODM/MongoDB/Query/Query.php
  lib/Doctrine/ODM/MongoDB/SchemaManager.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/AbstractCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/UpdateCommand.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/AlsoLoadTest.php
  tests/Documents/File.php
  tests/Documents/Functional/NotSaved.php
  tests/Documents/Functional/NotSavedEmbedded.php
Labels: feature

#1928 Use same documentation for notSaved in all annotations
  docs/en/reference/annotations-reference.rst
Labels: documentation

#1929 Fix serialisation of uninitialised PersistentCollection instances
  lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php
  tests/Doctrine/ODM/MongoDB/Tests/PersistentCollectionTest.php
Labels: bug

#1932 [2.0] Fix serialisation of uninitialised PersistentCollection instances
  lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php
  tests/Doctrine/ODM/MongoDB/Tests/PersistentCollectionTest.php
Labels: bug

#1936 Add configuration for stalebot
  .github/stale.yml
Labels: Task

#1937 Removed PHP 5.5 workaround
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
Labels: Task

#1939 Removed PHP 5.5 workaround
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
Labels: Task

#1944 fix: replace string assertion with array assertion for $filter
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateHydratorsCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GeneratePersistentCollectionsCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateProxiesCommand.php
Labels: Bug
