Repository doctrine/mongodb-odm, pull requests merged in 2019-12, with the labels that each got.

#2127 More tests for date_immutable type
  tests/Doctrine/ODM/MongoDB/Tests/Types/TypeTest.php
Labels: Task

#2130 Remove conflict markers
  docs/en/sidebar.rst
Labels: Documentation

#2131 FIX - info message must be lowercase
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateHydratorsCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GeneratePersistentCollectionsCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateProxiesCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateRepositoriesCommand.php
Labels: Bug

#2133 Fix typo in setup documentation
  docs/en/reference/introduction.rst
Labels: Documentation

#2139 Change Throwable to Exception for PHP 5.6
  lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
Labels: BC Break, Bug

#2143 #2093 final touches
  docs/en/cookbook/blending-orm-and-mongodb-odm.rst
Labels: Documentation
