Repository doctrine/mongodb-odm, pull requests merged in 2020-12, with the labels that each got.

#2229 Add psalm
  .github/workflows/static-analysis.yml
  composer.json
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ODM/MongoDB/Query/FilterCollection.php
  lib/Doctrine/ODM/MongoDB/Repository/DocumentRepository.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  phpstan-baseline.neon
  phpstan.neon.dist
  psalm.xml
Labels: Enhancement

#2260 Added missing check for order of compound keys
  lib/Doctrine/ODM/MongoDB/SchemaManager.php
  tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
Labels: Bug

#2261 Handle void return type in custom collection's methods
  lib/Doctrine/ODM/MongoDB/PersistentCollection/DefaultPersistentCollectionGenerator.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/CustomCollectionsTest.php
Labels: Bug

#2248 Provide initial compatibility with PHP 8
  .github/workflows/continuous-integration.yml
  UPGRADE-2.2.md
  composer.json
  lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/GeoNear.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/GraphLookup.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/GraphLookup/Match.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/GraphLookup/MatchStage.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Match.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/MatchStage.php
  lib/Doctrine/ODM/MongoDB/PersistentCollection/DefaultPersistentCollectionGenerator.php
  lib/Doctrine/ODM/MongoDB/Types/Versionable.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/AggregationTestTrait.php
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/MatchStageTest.php
  tests/Doctrine/ODM/MongoDB/Tests/BaseTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1344Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/AnnotationDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/XmlDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/XmlMappingDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/QueryTest.php
  tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
Labels: Task

#2264 add sort param to findOneBy with test
  lib/Doctrine/ODM/MongoDB/Repository/DocumentRepository.php
  tests/Doctrine/ODM/MongoDB/Tests/DocumentRepositoryTest.php
Labels: Feature
