Repository doctrine/mongodb-odm, pull requests merged in 2020-05, with the labels that each got.

#2011 [2.1] Deprecate AbstractIdGenerator
  UPGRADE-2.1.md
  lib/Doctrine/ODM/MongoDB/Id/AbstractIdGenerator.php
  lib/Doctrine/ODM/MongoDB/Id/IdGenerator.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
Labels: Enhancement

#2128 Add Decimal128 type
  composer.json
  docs/en/reference/annotations-reference.rst
  docs/en/reference/basic-mapping.rst
  docs/en/reference/storage-strategies.rst
  docs/en/reference/transactions-and-concurrency.rst
  lib/Doctrine/ODM/MongoDB/LockException.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
  lib/Doctrine/ODM/MongoDB/Types/Decimal128Type.php
  lib/Doctrine/ODM/MongoDB/Types/FloatType.php
  lib/Doctrine/ODM/MongoDB/Types/Incrementable.php
  lib/Doctrine/ODM/MongoDB/Types/IntType.php
  lib/Doctrine/ODM/MongoDB/Types/Type.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/FunctionalTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/LockTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverViewWithWrongRepository.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverViewWithoutRepository.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/Types/TypeTest.php
  tests/Documents/User.php
Labels: Feature

#2183 Favour bool and int over boolean and integer
  UPGRADE-2.1.md
  docs/en/cookbook/blending-orm-and-mongodb-odm.rst
  docs/en/cookbook/mapping-classes-to-orm-and-odm.rst
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Types/Type.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/IndexesTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/AbstractDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.QueryResultDocument.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.View.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/Persisters/DocumentPersisterGetShardKeyQueryTest.php
Labels: Task

#2184 Introduce Versionable interface
  docs/en/reference/annotations-reference.rst
  docs/en/reference/transactions-and-concurrency.rst
  lib/Doctrine/ODM/MongoDB/LockException.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  lib/Doctrine/ODM/MongoDB/Types/DateImmutableType.php
  lib/Doctrine/ODM/MongoDB/Types/DateType.php
  lib/Doctrine/ODM/MongoDB/Types/Decimal128Type.php
  lib/Doctrine/ODM/MongoDB/Types/IntType.php
  lib/Doctrine/ODM/MongoDB/Types/Versionable.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/LockTest.php
Labels: Task

#2186 Append ODM version info to driver metadata
  composer.json
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
Labels: Feature

#2185 Favour int over int_id
  UPGRADE-2.1.md
  lib/Doctrine/ODM/MongoDB/Id/AbstractIdGenerator.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Types/IntIdType.php
  lib/Doctrine/ODM/MongoDB/Types/Type.php
  tests/Doctrine/ODM/MongoDB/Tests/UnitOfWorkTest.php
Labels: Task

#2188 Typed properties support
  composer.json
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/TypedPropertiesTest.php
  tests/Documents74/TypedDocument.php
  tests/Documents74/TypedEmbeddedDocument.php
Labels: Enhancement

#2160 Bug/2157 Test (and fix) Facet's aggregation pipeline with DiscriminatorMap documents
  lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Facet.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2157Test.php
Labels: Bug

#2189 Fix prepareQueryOrNewObj with object values
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php
Labels: Bug

#2192 Better `convertToDatabaseValue`
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
Labels: Task
