Repository doctrine/mongodb-odm, pull requests merged in 2020-04, with the labels that each got.

#2166 Views
  docs/en/reference/annotations-reference.rst
  doctrine-mongo-mapping.xsd
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/View.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
  lib/Doctrine/ODM/MongoDB/MongoDBException.php
  lib/Doctrine/ODM/MongoDB/Repository/AbstractRepositoryFactory.php
  lib/Doctrine/ODM/MongoDB/Repository/ViewRepository.php
  lib/Doctrine/ODM/MongoDB/SchemaManager.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  lib/Doctrine/ODM/MongoDB/Utility/LifecycleEventManager.php
  tests/Doctrine/ODM/MongoDB/Tests/BaseTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ViewTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/AnnotationDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/View.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.View.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverView.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverViewWithNonExistingRootClass.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverViewWithWrongRepository.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverViewWithoutRepository.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverViewWithoutRootClass.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
  tests/Documents/UserName.php
  tests/Documents/UserNameRepository.php
  tests/Documents/ViewReference.php
Labels: Feature, Release Blocker

#2116 Provide rewindable option to Aggregation and Query builders/queries
  docs/en/reference/aggregation-builder.rst
  docs/en/reference/query-builder-api.rst
  lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage.php
  lib/Doctrine/ODM/MongoDB/Iterator/UnrewindableIterator.php
  lib/Doctrine/ODM/MongoDB/Query/Builder.php
  lib/Doctrine/ODM/MongoDB/Query/Query.php
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/BuilderTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Iterator/UnrewindableIteratorTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/BuilderTest.php
  tests/Doctrine/ODM/MongoDB/Tests/QueryTest.php
Labels: Enhancement

#2177 Use majority write concern to fix flaky test
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ReadPreferenceTest.php
Labels: Task
