Repository doctrine/mongodb-odm, pull requests merged in 2020-11, with the labels that each got.

#2239 Assert array value is an instance of the key
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
Labels: Task

#2235 Document class-level Index annotations and deprecate other ways of specifying them
  UPGRADE-2.2.md
  docs/en/reference/annotations-reference.rst
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Indexes.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/IndexesTest.php
Labels: Documentation, Task

#2240 Remove phpstan error formatter
  .github/workflows/static-analysis.yml
Labels: Task

#2231 Update PHPStan
  .github/workflows/static-analysis.yml
  composer.json
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php
  lib/Doctrine/ODM/MongoDB/Repository/AbstractRepositoryFactory.php
  phpstan-baseline.neon
  phpstan.neon.dist
Labels: Task

#2244 Fix trigger_error level when deprecated type is used
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
Labels: Bug

#2249 Use symfony/deprecation-contracts to announce deprecations in code
  composer.json
  lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage.php
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/AbstractField.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
Labels: Enhancement
