Repository doctrine/mongodb-odm, pull requests merged in 2020-01, with the labels that each got.

#2146 Fix reading custom repository class for GridFS XML mappings
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverFileWithCustomRepository.dcm.xml
Labels: Bug

#2148 Ignore missing background option when comparing indexes
  lib/Doctrine/ODM/MongoDB/SchemaManager.php
  tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
Labels: Bug

#2150 Address deprecations from persistence
  composer.json
  docs/en/cookbook/mapping-classes-to-orm-and-odm.rst
  lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/GraphLookup.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Lookup.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Out.php
  lib/Doctrine/ODM/MongoDB/Configuration.php
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  lib/Doctrine/ODM/MongoDB/Event/LifecycleEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/LoadClassMetadataEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/ManagerEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/OnClearEventArgs.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/SimplifiedXmlDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
  lib/Doctrine/ODM/MongoDB/MongoDBException.php
  lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionInterface.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  lib/Doctrine/ODM/MongoDB/Repository/AbstractRepositoryFactory.php
  lib/Doctrine/ODM/MongoDB/Repository/DefaultRepositoryFactory.php
  lib/Doctrine/ODM/MongoDB/Repository/DocumentRepository.php
  lib/Doctrine/ODM/MongoDB/Repository/GridFSRepository.php
  lib/Doctrine/ODM/MongoDB/Repository/RepositoryFactory.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Symfony/AbstractDriverTest.php
Labels: Task

#2155 Bump doctrine/persistence
  composer.json
Labels: Task

#2158 Typo in introduction
  docs/en/reference/introduction.rst
Labels: Documentation

#2159 Deprecation and forward compat for flush
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
Labels: Task
