Repository doctrine/mongodb-odm, pull requests merged in 2021-10, with the labels that each got.

#2373 Improve phpdoc
  lib/Doctrine/ODM/MongoDB/Event/OnClassMetadataNotFoundEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/PostCollectionLoadEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/PreLoadEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/PreUpdateEventArgs.php
  lib/Doctrine/ODM/MongoDB/Hydrator/HydratorException.php
  lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php
  lib/Doctrine/ODM/MongoDB/Hydrator/HydratorInterface.php
  lib/Doctrine/ODM/MongoDB/Proxy/Factory/ProxyFactory.php
  lib/Doctrine/ODM/MongoDB/Proxy/Factory/StaticProxyFactory.php
  lib/Doctrine/ODM/MongoDB/Proxy/Resolver/ClassNameResolver.php
  lib/Doctrine/ODM/MongoDB/Repository/AbstractRepositoryFactory.php
  lib/Doctrine/ODM/MongoDB/Repository/DefaultGridFSRepository.php
  lib/Doctrine/ODM/MongoDB/Repository/DocumentRepository.php
  lib/Doctrine/ODM/MongoDB/SchemaManager.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateProxiesCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/ValidateCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/MetadataFilter.php
  lib/Doctrine/ODM/MongoDB/Tools/ResolveTargetDocumentListener.php
  lib/Doctrine/ODM/MongoDB/Types/Type.php
  lib/Doctrine/ODM/MongoDB/Utility/LifecycleEventManager.php
Labels: Task

#2377 Describe better types in phpdoc for Iterators
  lib/Doctrine/ODM/MongoDB/Iterator/CachingIterator.php
  lib/Doctrine/ODM/MongoDB/Iterator/HydratingIterator.php
  lib/Doctrine/ODM/MongoDB/Iterator/PrimingIterator.php
  lib/Doctrine/ODM/MongoDB/Iterator/UnrewindableIterator.php
Labels: Task

#2379 Remove deprecated "boolean" mapping type in docs
  docs/en/reference/basic-mapping.rst
Labels: Documentation

#2372 support wildcard index mapping
  doctrine-mongo-mapping.xsd
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/XmlDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/WildcardIndexDocument.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.WildcardIndexDocument.dcm.xml
Labels: Bug
