Repository doctrine/mongodb-odm, pull requests merged in 2021-05, with the labels that each got.

#2306 Run stable versions of phpbench
  composer.json
  phpbench.json
Labels: Task

#2304 Use proxy class name resolvers instead of local workaround
  UPGRADE-2.3.md
  UPGRADE-3.0.md
  composer.json
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ODM/MongoDB/Proxy/Resolver/CachingClassNameResolver.php
  lib/Doctrine/ODM/MongoDB/Proxy/Resolver/ClassNameResolver.php
  lib/Doctrine/ODM/MongoDB/Proxy/Resolver/ProxyManagerClassNameResolver.php
  tests/Doctrine/ODM/MongoDB/Tests/RepositoryFactoryTest.php
Labels: Enhancement

#2307 Allow mixed value in $not operator
  lib/Doctrine/ODM/MongoDB/Query/Builder.php
  lib/Doctrine/ODM/MongoDB/Query/Expr.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/QueryTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/BuilderTest.php
Labels: Bug

#2308 Make ClassMetadata generic
  lib/Doctrine/ODM/MongoDB/Iterator/Iterator.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  lib/Doctrine/ODM/MongoDB/Repository/DocumentRepository.php
  phpstan-baseline.neon
Labels: Documentation

#2309 Upgrade to doctrine/coding-standard 9
  composer.json
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  lib/Doctrine/ODM/MongoDB/Proxy/Resolver/ProxyManagerClassNameResolver.php
  lib/Doctrine/ODM/MongoDB/Repository/DocumentRepository.php
  lib/Doctrine/ODM/MongoDB/Repository/RepositoryFactory.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  phpcs.xml.dist
Labels: Task

#2313 Fix some phpdoc
  lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/AbstractBucket.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Bucket.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/ReplaceRoot.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
Labels: Enhancement

#2315 Ignore parent parameter name mismatch
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php
  lib/Doctrine/ODM/MongoDB/Query/QueryExpressionVisitor.php
Labels: Documentation

#2238 JSON Schema Validation
  docs/en/cookbook/validation-of-documents.rst
  docs/en/reference/annotations-reference.rst
  doctrine-mongo-mapping.xsd
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Validation.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
  lib/Doctrine/ODM/MongoDB/SchemaManager.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/UpdateCommand.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ValidationTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/AnnotationDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Annotations/ValidationTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/XmlDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/SchemaInvalidDocument.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/SchemaValidatedDocument.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.SchemaInvalidDocument.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.SchemaValidatedDocument.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Tools/Console/Command/AbstractCommandTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Tools/Console/Command/Schema/UpdateCommandTest.php
  tests/Documents/SchemaValidated.php
Labels: Feature

#2312 Improve phpdoc specification
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ODM/MongoDB/Repository/AbstractRepositoryFactory.php
Labels: Documentation
