Repository doctrine/mongodb-odm, pull requests merged in 2021-02, with the labels that each got.

#2275 Allow PrettyVersion 2
  composer.json
Labels: Task

#2281 Fix locking when ClassMetadata is unserialized
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
Labels: Bug

#2285 Update working-with-objects.rst
  docs/en/reference/working-with-objects.rst
Labels: Documentation

#2286 Update storage-strategies.rst
  docs/en/reference/storage-strategies.rst
Labels: Documentation

#2290 Fix invalid strict comparison when validating mappings
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/ValidateCommand.php
Labels: Bug

#2288 Set type maps on collection level
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  tests/Doctrine/ODM/MongoDB/Tests/DocumentManagerTest.php
  tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
Labels: Enhancement
