Repository doctrine/mongodb-odm, pull requests merged in 2021-01, with the labels that each got.

#2263 Add support for PHP 8.0 types in custom collection
  .github/workflows/continuous-integration.yml
  .github/workflows/static-analysis.yml
  lib/Doctrine/ODM/MongoDB/PersistentCollection/DefaultPersistentCollectionGenerator.php
  phpcs.xml.dist
  phpstan.neon.dist
  tests/Doctrine/ODM/MongoDB/Tests/PersistentCollection/CollWithPHP80Types.php
  tests/Doctrine/ODM/MongoDB/Tests/PersistentCollection/DefaultPersistentCollectionGeneratorTest.php
Labels: Feature

#2270 Bump doctrine/coding-standard follow up
  phpcs.xml.dist
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/MODM117Test.php
Labels: Task

#2271 Deprecate mapping relations with targetDocument and discriminatorMap
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH267Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.xml
Labels: Bug

#2272 Run tests on sharded clusters
  .github/workflows/continuous-integration.yml
  tests/Doctrine/ODM/MongoDB/Tests/BaseTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ReadPreferenceTest.php
Labels: Task
