Repository doctrine/mongodb-odm, pull requests merged in 2021-08, with the labels that each got.

#2352 Ignore unreachable statement
  lib/Doctrine/ODM/MongoDB/Types/DateImmutableType.php
Labels: Task

#2351 Fix missing hint query option during find
  lib/Doctrine/ODM/MongoDB/Query/Query.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/BuilderTest.php
  tests/Doctrine/ODM/MongoDB/Tests/QueryTest.php
Labels: Bug

#2353 allow to reset hydration setting for Aggregation
  lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/BuilderTest.php
Labels: Bug

#2359 flip attribute driver constructor arguments
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/AttributeDriver.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/AttributeDriverTest.php
Labels: Enhancement

#2360 use @requires annotations to skip tests on older PHP versions
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2310Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/TypedPropertiesTest.php
  tests/Doctrine/ODM/MongoDB/Tests/PersistentCollection/DefaultPersistentCollectionGeneratorTest.php
Labels: Task
