Repository doctrine/mongodb-odm, pull requests merged in 2021-06, with the labels that each got.

#2314 Describe iterable type arrays
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
Labels: Documentation

#2319 [2.2] Fix builds
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/performance.yml
  .github/workflows/static-analysis.yml
  composer.json
  phpbench.json
  phpstan-baseline.neon
  psalm-baseline.xml
  psalm.xml
Labels: Task

#2320 Add generics to UoW methods and `DocumentManager::getReference`
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  lib/Doctrine/ODM/MongoDB/Proxy/Factory/ProxyFactory.php
  lib/Doctrine/ODM/MongoDB/Repository/DocumentRepository.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
Labels: Documentation

#2317 Add tests directory to phpstan
  composer.json
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  phpstan-baseline.neon
  phpstan.neon.dist
  tests/Doctrine/ODM/MongoDB/Tests/BaseTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/AtomicSetTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/QueryTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH593Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH602Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH852Test.php
  tests/Doctrine/ODM/MongoDB/Tests/HydratorTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
  tests/Documents/User.php
  tests/Documents/ViewReference.php
Labels: Task

#2321 Fix phpstan build
  phpstan-baseline.neon
  tests/Doctrine/ODM/MongoDB/Tests/HydratorTest.php
Labels: Task

#2318 Fix wrong handling for nullable fields in upsert and update
  lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/EmbeddedTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2310Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/UpsertTest.php
  tests/Documents/User.php
  tests/Documents74/GH2310Container.php
Labels: Bug

#2326 Add more specific phpdoc to `DocumentRepository`
  composer.json
  lib/Doctrine/ODM/MongoDB/Repository/DocumentRepository.php
  phpstan-baseline.neon
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
Labels: Documentation

#2327 Fix some issues of Psalm in level 6
  phpstan-baseline.neon
  tests/Doctrine/ODM/MongoDB/Tests/Functional/AtomicSetTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/CustomCollectionsTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/EcommerceTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/IdTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/QueryTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1011Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1428Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2157Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/MODM90Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
  tests/Doctrine/ODM/MongoDB/Tests/PersistentCollectionTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/BuilderTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/ExprTest.php
  tests/Doctrine/ODM/MongoDB/Tests/QueryTest.php
  tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Types/DateImmutableTypeTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Types/DateTypeTest.php
  tests/Documents/CmsArticle.php
  tests/Documents/Functional/Ticket/GH683/ParentDocument.php
Labels: Task

#2324 Make `PersistentCollectionInterface` and `PersistentCollection` generic
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/PersistentCollection.php
  lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionInterface.php
  lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php
  phpstan-baseline.neon
  tests/Doctrine/ODM/MongoDB/Tests/PersistentCollectionTest.php
Labels: Task

#2330 Add more phpdoc type info
  tests/Doctrine/ODM/MongoDB/Tests/Functional/AtomicSetTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/EmbeddedTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferenceEmbeddedDocumentsTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1011Test.php
  tests/Documents/Book.php
  tests/Documents/IdentifiedChapter.php
  tests/Documents/Project.php
  tests/Documents/SubProject.php
Labels: Typing

#2333 Add return static
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/MatchStage.php
  phpstan-baseline.neon
Labels: Typing

#2334 Fix handling of upserts during scheduling for deletion
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  tests/Doctrine/ODM/MongoDB/Tests/UnitOfWorkTest.php
Labels: Bug
