Repository doctrine/mongodb-odm, pull requests merged in 2022-11, with the labels that each got.

#2437 Add PHPStan check for iterable types
  benchmark/Document/HydrateDocumentBench.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Lookup.php
  lib/Doctrine/ODM/MongoDB/Iterator/HydratingIterator.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  phpstan-baseline.neon
  phpstan.neon.dist
  psalm-baseline.xml
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/AggregationOperatorsProviderTrait.php
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/ExprTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/GraphLookupTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/GroupTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/OperatorTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/ProjectTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/SortTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Events/LifecycleListenersTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Events/PreUpdateEventArgsTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/CommitImprovementTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Iterator/CachingIteratorTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Iterator/HydratingIteratorTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Iterator/UnrewindableIteratorTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ReadPreferenceTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferenceDiscriminatorsTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1232Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2002Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH560Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH597Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/MODM62Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/MODM81Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/MODM83Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/MODM90Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/MODM91Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/MODM95Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Symfony/AbstractDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/PersistentCollectionTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Persisters/PersistenceBuilderTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/BuilderTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/CriteriaMergerTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/ExprTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/QueryExpressionVisitorTest.php
  tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
  tests/Doctrine/ODM/MongoDB/Tests/UnitOfWorkTest.php
  tests/Documents/Article.php
  tests/Documents/BaseEmployee.php
  tests/Documents/SpecialUser.php
  tests/Documents/User.php
  tests/Documents74/UserTyped.php
Labels: Enhancement

#2484 PHPStan 1.9.2
  composer.json
  phpstan-baseline.neon
Labels: Task

#2485 Fix deprecation notices in CommandLogger
  lib/Doctrine/ODM/MongoDB/APM/CommandLogger.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
  phpstan-baseline.neon
Labels: Bug
