Repository doctrine/mongodb-odm, pull requests merged in 2022-03, with the labels that each got.

#2416 Fix typo in method name
  docs/en/reference/aggregation-builder.rst
Labels: Documentation

#2417 Fix PHPStan build
  tests/Doctrine/ODM/MongoDB/Tests/Functional/AtomicSetTest.php
Labels: Task

#2411 Use typed properties for default metadata
  UPGRADE-2.4.md
  docs/en/reference/annotations-reference.rst
  docs/en/reference/basic-mapping.rst
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/AbstractField.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Documents74.UserTyped.dcm.xml
  tests/Documents74/CustomCollection.php
  tests/Documents74/UserTyped.php
Labels: Feature

#2420 Use colocated mapping driver
  UPGRADE-2.4.md
  composer.json
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
Labels: Task
