Repository doctrine/mongodb-odm, pull requests merged in 2022-05, with the labels that each got.

#2434 Deprecate NOTIFY tracking policy
  UPGRADE-2.4.md
  UPGRADE-3.0.md
  docs/en/cookbook/implementing-the-notify-changetracking-policy.rst
  docs/en/reference/change-tracking-policies.rst
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
Labels: Task

#2438 Leverage generic persistence event classes
  lib/Doctrine/ODM/MongoDB/Event/LifecycleEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/LoadClassMetadataEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/ManagerEventArgs.php
  lib/Doctrine/ODM/MongoDB/Event/OnClearEventArgs.php
Labels: Enhancement

#2442 Remove targetDocument autocompletion
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Documents74.UserTyped.dcm.xml
  tests/Documents74/UserTyped.php
Labels: Task

#2443 Compatibility layer for AnnotationDriver
  UPGRADE-2.4.md
  UPGRADE-3.0.md
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/CompatibilityAnnotationDriver.php
  phpcs.xml.dist
Labels: Task

#2445 Fix Builder::getAggregation $options parameter type
  lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
Labels: Bug

#2446 Fix EnumReflectionProperty ClassMetadata deserialization
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
Labels: Bug

#2447 Allow using enums directly in queries
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/EnumTest.php
Labels: Bug

#2449 Specify class-string return type
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
Labels: Enhancement
