Repository doctrine/mongodb-odm, pull requests merged in 2023-10, with the labels that each got.

#2553 Backport cleanup #2544
  .github/workflows/continuous-integration.yml
  .github/workflows/performance.yml
  .github/workflows/static-analysis.yml
  docs/en/cookbook/soft-delete-extension.rst
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Validation.php
  lib/Doctrine/ODM/MongoDB/Proxy/Factory/StaticProxyFactory.php
  phpstan-baseline.neon
  psalm-baseline.xml
  tests/Doctrine/ODM/MongoDB/Tests/Events/LifecycleCallbacksTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/DocumentPersisterTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/HasLifecycleCallbacksTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/IndexesTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/LifecycleTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/LockTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/PrePersistTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH897Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH999Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/MODM116Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/MODM43Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/MODM56Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Documents/GlobalNamespaceDocument.php
  tests/Documents/BaseDocument.php
  tests/Documents/Functional/EmbeddedTestLevel1.php
  tests/Documents/Functional/EmbeddedTestLevel2.php
  tests/Documents/ProfileNotify.php
  tests/Documents/SimpleReferenceUser.php
Labels: Task

#2552 Introduce ClassMetadataFactoryInterface to allow switching implementations
  lib/Doctrine/ODM/MongoDB/Configuration.php
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactoryInterface.php
  lib/Doctrine/ODM/MongoDB/MongoDBException.php
  lib/Doctrine/ODM/MongoDB/SchemaManager.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/AbstractCommand.php
  phpstan-baseline.neon
  psalm-baseline.xml
  tests/Doctrine/ODM/MongoDB/Tests/Tools/ResolveTargetDocumentListenerTest.php
Labels: Bug, BC Break

#2532 Test persisting array of enums
  tests/Doctrine/ODM/MongoDB/Tests/Functional/EnumTest.php
  tests/Documents81/Card.php
Labels: Enhancement

#2556 Require PHP 8.1
  .github/workflows/continuous-integration.yml
  .github/workflows/performance.yml
  UPGRADE-2.6.md
  composer.json
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
  phpcs.xml.dist
  phpstan-baseline.neon
  tests/Doctrine/ODM/MongoDB/Tests/Functional/EnumTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTestCase.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Documents.Card.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/PersistentCollection/DefaultPersistentCollectionGeneratorTest.php
  tests/Documents/Card.php
  tests/Documents/Suit.php
  tests/Documents/SuitInt.php
  tests/Documents/SuitNonBacked.php
Labels: Task

#2558 feat: Symfony 7 support
  composer.json
Labels: Task

#2557 Remove unusable Match classes
  UPGRADE-2.6.md
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/GraphLookup/Match.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Match.php
  phpcs.xml.dist
  phpstan.neon.dist
  phpunit.xml.dist
  psalm.xml.dist
Labels: Task

#2547 ReferenceMany: insert an empty array
  docs/en/reference/embedded-mapping.rst
  docs/en/reference/reference-mapping.rst
  doctrine-mongo-mapping.xsd
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/EmbedMany.php
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/ReferenceMany.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php
  lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/CollectionPersisterTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/AbstractDriverTestCase.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/fixtures/xml/TestDocuments.PrimedCollectionDocument.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/Persisters/PersistenceBuilderTest.php
  tests/Documents/Ecommerce/Basket.php
  tests/Documents/Ecommerce/Order.php
Labels: Feature

#2559 Drop support for symfony components <5.4
  composer.json
Labels: Task

#2560 Last PHP 8.1 chores
  phpcs.xml.dist
  psalm.xml.dist
  tests/Doctrine/ODM/MongoDB/Tests/PersistentCollection/CollWithPHP80Types.php
  tests/Doctrine/ODM/MongoDB/Tests/PersistentCollection/CollWithPHP81Types.php
Labels: Task

#2562 Add PHP 8.3 to CI
  .github/workflows/continuous-integration.yml
Labels: Task

#2563 Support Symfony 7 by adding return types conditionally
  .github/workflows/continuous-integration.yml
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/ClearCache/MetadataCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/CommandCompatibility.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateHydratorsCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GeneratePersistentCollectionsCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/GenerateProxiesCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/QueryCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/DropCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/ShardCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/UpdateCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/ValidateCommand.php
  lib/Doctrine/ODM/MongoDB/Tools/Console/Helper/DocumentManagerHelper.php
  phpcs.xml.dist
  psalm-baseline.xml
Labels: Task

#2565 Doctrine CS 12
  composer.json
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
  psalm-baseline.xml
Labels: Task

#2566 Bump workflows
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/performance.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
Labels: Task
