Repository doctrine/mongodb-odm, pull requests merged in 2023-11, with the labels that each got.

#2569 Implement ObjectManager::isUninitializedObject
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/IdentifiersTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencePrimerTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencesTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/SimpleReferencesTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH520Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH593Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH602Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH852Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
Labels: Feature

#2567 Enable Dependabot for Github Actions
  .github/dependabot.yml
Labels: Task

#2570 Preserve iterator position when counting
  lib/Doctrine/ODM/MongoDB/Iterator/CachingIterator.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Iterator/CachingIteratorTest.php
Labels: Bug

#2575 fix: Do not drop/re-create 2dsphere indexes
  lib/Doctrine/ODM/MongoDB/SchemaManager.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/IndexesTest.php
  tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
Labels: Bug

#2577 Validate that targetDocument can be resolved
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/TargetDocumentTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/TestTargetDocument.php
Labels: Bug

#2554 Add sort operator to $search stage
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Search.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Search/AbstractSearchOperator.php
  phpstan-baseline.neon
  phpstan.neon.dist
  psalm-baseline.xml
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/SearchTest.php
Labels: Enhancement

#2583 Support minDistance and maxDistance options for $near and $nearSphere operators
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  lib/Doctrine/ODM/MongoDB/Query/Builder.php
  lib/Doctrine/ODM/MongoDB/Query/Expr.php
  lib/Doctrine/ODM/MongoDB/Types/Type.php
  psalm-baseline.xml
  tests/Doctrine/ODM/MongoDB/Tests/Query/BuilderTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Query/ExprTest.php
Labels: Enhancement

#2590 Fix missing storeEmptyArray attribute for embed relationships in XML driver
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTestCase.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/Driver/AbstractDriverTestCase.php
Labels: Bug
