Repository doctrine/mongodb-odm, pull requests merged in 2025-03, with the labels that each got.

#2737 Fix duplicate object hash for removed object
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2730Test.php
Labels: Bug

#2738 Replace `spl_object_hash` with `spl_object_id`
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  lib/Doctrine/ODM/MongoDB/Repository/AbstractRepositoryFactory.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  lib/Doctrine/ODM/MongoDB/Utility/LifecycleEventManager.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1017Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Mocks/PreUpdateListenerMock.php
  tests/Doctrine/ODM/MongoDB/Tests/UnitOfWorkTest.php
Labels: Enhancement

#2741 Replace "attribute" with "argument" to avoid confusion with PHP attributes
  docs/en/cookbook/time-series-data.rst
  docs/en/reference/attributes-reference.rst
  docs/en/reference/basic-mapping.rst
  docs/en/reference/search-indexes.rst
  docs/en/reference/storing-files-with-gridfs.rst
Labels: Documentation

#2739 Add support for using `$text` operator in a aggregation with a filter
  lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/BuilderTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/GeoNearTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/FilterTest.php
Labels: Bug

#2743 Fix `$geoNear` stage with empty query
  lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/GeoNear.php
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/GeoNearTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/GeoTest.php
  tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
  tests/Documents/Place.php
Labels: Bug

#2740 Skip empty `$match` from pipeline builder
  lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/MatchStage.php
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/BuilderTest.php
Labels: Feature

#2746 Fix RST formatting for warning content
  docs/en/reference/transactions-and-concurrency.rst
Labels: Documentation
