Repository doctrine/mongodb-odm, pull requests merged in 2025-09, with the labels that each got.

#2816 Fix duplicate slug in .doctrine-project.json
  .doctrine-project.json
Labels: Task

#2811 Update test using deprecated field type `integer`
  tests/Documents/GH2310Container.php
Labels: Task

#2812 Format evaled code with heredoc in tests
  tests/Doctrine/ODM/MongoDB/Tests/Functional/IdTest.php
Labels: Task

#2813 Convert the value of the "version" field using its known type
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2789Test.php
Labels: Bug

#2815 Enable optimistic locking using an `ObjectId` as version field
  docs/en/reference/transactions-and-concurrency.rst
  lib/Doctrine/ODM/MongoDB/Types/ObjectIdType.php
  tests/Doctrine/ODM/MongoDB/Tests/Types/VersionableTest.php
Labels: Feature

#2820 PHPORM-381 Add class metadata for vector search indexes
  docs/en/reference/attributes-reference.rst
  doctrine-mongo-mapping.xsd
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/SearchIndex.php
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/VectorSearchIndex.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/AttributeDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
  phpstan-baseline.neon
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTestCase.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Doctrine.ODM.MongoDB.Tests.Mapping.AbstractMappingDriverUser.dcm.xml
  tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
  tests/Documents/CmsArticle.php
  tests/Documents/VectorEmbedding.php
Labels: Feature

#2822 PHPORM-382 Add $vectorSearch stage to the aggregation builder
  docs/en/reference/aggregation-stage-reference.rst
  lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/VectorSearch.php
  tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/VectorSearchTest.php
Labels: Feature

#2826 Support symfony UUID
  UPGRADE-3.0.md
  composer.json
  docs/en/reference/basic-mapping.rst
  lib/Doctrine/ODM/MongoDB/Id/AutoGenerator.php
  lib/Doctrine/ODM/MongoDB/Id/ObjectIdGenerator.php
  lib/Doctrine/ODM/MongoDB/Id/SymfonyUuidGenerator.php
  lib/Doctrine/ODM/MongoDB/Id/UuidGenerator.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
  lib/Doctrine/ODM/MongoDB/Types/BinaryUuidType.php
  lib/Doctrine/ODM/MongoDB/Types/Type.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  phpstan-baseline.neon
  tests/Doctrine/ODM/MongoDB/Tests/Functional/UuidMappingTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Types/BinaryUuidTypeTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Types/TypeTest.php
Labels: Feature

#2829 Add test on Atlas Search features using an MongoDB Atlas Local Docker
  .github/workflows/atlas-ci.yml
  .github/workflows/continuous-integration.yml
  docker-compose.yaml
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  tests/Doctrine/ODM/MongoDB/Tests/BaseTestCase.php
  tests/Doctrine/ODM/MongoDB/Tests/Events/TransactionalLifecycleEventsTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/AtlasSearchTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/VectorSearchTest.php
  tests/Doctrine/ODM/MongoDB/Tests/UnitOfWorkCommitConsistencyTest.php
  tests/Doctrine/ODM/MongoDB/Tests/UnitOfWorkTransactionalCommitConsistencyTest.php
Labels: Enhancement

#2835 Ignore PHPStan errors for unused properties in document classes
  phpstan-baseline.neon
  phpstan.neon.dist
  tests/Doctrine/ODM/MongoDB/Tests/Functional/DatabasesTest.php
  tests/Doctrine/ODM/MongoDB/Tests/UnitOfWorkTest.php
Labels: Task

#2837 Exclude non-essential fields from the archive
  .gitattributes
Labels: Enhancement

#2843 Use null coalescing operator `??` and `??=`
  lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/AbstractBucket.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/AbstractReplace.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/GraphLookup.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Search/Compound.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Proxy/Resolver/CachingClassNameResolver.php
  lib/Doctrine/ODM/MongoDB/Query/Builder.php
  lib/Doctrine/ODM/MongoDB/Query/Expr.php
Labels: Enhancement
