Repository doctrine/mongodb-odm, pull requests merged in 2025-01, with the labels that each got.

#2716 Fix discriminatorValue key 0
  lib/Doctrine/ODM/MongoDB/Mapping/Annotations/DiscriminatorMap.php
  lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2158Test.php
Labels: Bug

#2717 Relax final constraints on stage classes
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/AddFields.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Set.php
Labels: Bug

#2702 Improve query and aggregator classes
  lib/Doctrine/ODM/MongoDB/Aggregation/Aggregation.php
  lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
  lib/Doctrine/ODM/MongoDB/Iterator/IterableResult.php
  lib/Doctrine/ODM/MongoDB/Query/Builder.php
  lib/Doctrine/ODM/MongoDB/Query/Query.php
Labels: Enhancement

#2700 Switch proxies to `LazyGhostTrait`
  .github/workflows/continuous-integration.yml
  composer.json
  lib/Doctrine/ODM/MongoDB/Configuration.php
  lib/Doctrine/ODM/MongoDB/DocumentManager.php
  lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php
  lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
  lib/Doctrine/ODM/MongoDB/Proxy/Autoloader.php
  lib/Doctrine/ODM/MongoDB/Proxy/Factory/LazyGhostProxyFactory.php
  lib/Doctrine/ODM/MongoDB/Proxy/Factory/ProxyFactory.php
  lib/Doctrine/ODM/MongoDB/Proxy/Factory/StaticProxyFactory.php
  lib/Doctrine/ODM/MongoDB/Proxy/InternalProxy.php
  lib/Doctrine/ODM/MongoDB/Proxy/Resolver/LazyGhostProxyClassNameResolver.php
  lib/Doctrine/ODM/MongoDB/UnitOfWork.php
  phpstan-baseline.neon
  phpunit.xml.dist
  tests/Doctrine/ODM/MongoDB/Tests/BaseTestCase.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/IdentifiersTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencePrimerTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferencesTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/SimpleReferencesTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH520Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH593Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH602Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH852Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH936Test.php
  tests/Doctrine/ODM/MongoDB/Tests/Functional/ViewTest.php
  tests/Doctrine/ODM/MongoDB/Tests/HydratorTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php
  tests/Doctrine/ODM/MongoDB/Tests/Proxy/Factory/ProxyFactoryTest.php
  tests/Doctrine/ODM/MongoDB/Tests/UnitOfWorkTest.php
Labels: Enhancement

#2720 Keep proxy-manager by default
  .github/workflows/continuous-integration.yml
  composer.json
  lib/Doctrine/ODM/MongoDB/Configuration.php
Labels: Bug

#2721 Create website schema validation workflow
  .github/workflows/website-schema.yml
Labels: CI
